"""create_initial_schema

Revision ID: 384449b50453
Revises: 
Create Date: 2026-09-20 22:01:02.324163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '384449b50453'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('plan_tier', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_query_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('generated_sql', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('rows_count', sa.Integer(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_query_org_created', 'ai_query_log', ['org_id', 'created_at'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('threshold_percent', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_rules_org', 'alert_rules', ['org_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('stripe_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('delinquent', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'stripe_id', name='uq_customers_org_stripe_id')
    )
    op.create_index('idx_customers_org_id', 'customers', ['org_id'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=255), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_org_status', 'jobs', ['org_id', 'status'], unique=False)
    op.create_index('idx_jobs_run_at_pending', 'jobs', ['run_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index(op.f('ix_jobs_org_id'), 'jobs', ['org_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id', name='uq_memberships_org_user')
    )
    op.create_index(op.f('ix_memberships_org_id'), 'memberships', ['org_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('stripe_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('interval', sa.String(length=50), nullable=False),
    sa.Column('interval_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'stripe_id', name='uq_plans_org_stripe_id')
    )
    op.create_index('idx_plans_org_id', 'plans', ['org_id'], unique=False)
    op.create_table('stripe_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_connections_org_id'), 'stripe_connections', ['org_id'], unique=True)
    op.create_table('stripe_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('stripe_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'created_at'),
    sa.UniqueConstraint('org_id', 'stripe_event_id', 'created_at', name='uq_stripe_events_org_event_created'),
    postgresql_partition_by='RANGE (created_at)'
    )
    op.create_index('idx_stripe_events_org_type', 'stripe_events', ['org_id', 'event_type'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_org_triggered', 'alerts', ['org_id', 'triggered_at'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('stripe_id', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'stripe_id', name='uq_subscriptions_org_stripe_id')
    )
    op.create_index('idx_subscriptions_org_cust', 'subscriptions', ['org_id', 'customer_id'], unique=False)
    op.create_index('idx_subscriptions_org_status', 'subscriptions', ['org_id', 'status'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('stripe_id', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('amount_due_cents', sa.BigInteger(), nullable=False),
    sa.Column('amount_paid_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'stripe_id', name='uq_invoices_org_stripe_id')
    )
    op.create_index('idx_invoices_org_created', 'invoices', ['org_id', 'created_at'], unique=False)
    op.create_index('idx_invoices_org_status', 'invoices', ['org_id', 'status'], unique=False)
    op.create_table('mrr_daily',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('mrr_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_id', 'date', 'subscription_id', name='pk_mrr_daily')
    )
    op.create_index('idx_mrr_daily_org_cust', 'mrr_daily', ['org_id', 'customer_id'], unique=False)
    op.create_index('idx_mrr_daily_org_date', 'mrr_daily', ['org_id', 'date'], unique=False)
    op.create_table('mrr_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('prior_mrr_cents', sa.BigInteger(), nullable=False),
    sa.Column('current_mrr_cents', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mrr_movements_org_date', 'mrr_movements', ['org_id', 'date'], unique=False)
    op.create_index('idx_mrr_movements_org_type', 'mrr_movements', ['org_id', 'movement_type'], unique=False)
    op.create_table('subscription_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('stripe_id', sa.String(length=255), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'stripe_id', name='uq_sub_items_org_stripe_id')
    )
    op.create_index('idx_sub_items_org_sub', 'subscription_items', ['org_id', 'subscription_id'], unique=False)

    # --------------------------------------------------------------------------
    # 1. PARTITIONS FOR stripe_events
    # --------------------------------------------------------------------------
    op.execute("""
    CREATE TABLE IF NOT EXISTS stripe_events_default PARTITION OF stripe_events DEFAULT;
    CREATE TABLE IF NOT EXISTS stripe_events_y2025 PARTITION OF stripe_events
        FOR VALUES FROM ('2025-01-01 00:00:00+00') TO ('2026-01-01 00:00:00+00');
    CREATE TABLE IF NOT EXISTS stripe_events_y2026 PARTITION OF stripe_events
        FOR VALUES FROM ('2026-01-01 00:00:00+00') TO ('2027-01-01 00:00:00+00');
    CREATE TABLE IF NOT EXISTS stripe_events_y2027 PARTITION OF stripe_events
        FOR VALUES FROM ('2027-01-01 00:00:00+00') TO ('2028-01-01 00:00:00+00');
    """)

    # --------------------------------------------------------------------------
    # 2. ROW-LEVEL SECURITY (RLS) ON ALL TENANT TABLES
    # --------------------------------------------------------------------------
    tenant_tables = [
        "memberships",
        "stripe_connections",
        "customers",
        "plans",
        "subscriptions",
        "subscription_items",
        "invoices",
        "stripe_events",
        "mrr_daily",
        "mrr_movements",
        "alert_rules",
        "alerts",
        "ai_query_log",
    ]

    # Organizations table uses id = current_org_id for select/update/delete, allows insert for onboarding
    op.execute("""
    ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;
    ALTER TABLE organizations FORCE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_org_isolation ON organizations;
    DROP POLICY IF EXISTS org_select_policy ON organizations;
    DROP POLICY IF EXISTS org_insert_policy ON organizations;
    DROP POLICY IF EXISTS org_update_delete_policy ON organizations;

    CREATE POLICY org_select_policy ON organizations
        FOR SELECT
        USING (id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

    CREATE POLICY org_insert_policy ON organizations
        FOR INSERT
        WITH CHECK (true);

    CREATE POLICY org_update_delete_policy ON organizations
        FOR UPDATE
        USING (id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        WITH CHECK (id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
    """)

    for tbl in tenant_tables:
        op.execute(f"""
        ALTER TABLE {tbl} ENABLE ROW LEVEL SECURITY;
        ALTER TABLE {tbl} FORCE ROW LEVEL SECURITY;
        DROP POLICY IF EXISTS tenant_isolation_policy ON {tbl};
        CREATE POLICY tenant_isolation_policy ON {tbl}
            FOR ALL
            USING (org_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
            WITH CHECK (org_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
        """)

    # --------------------------------------------------------------------------
    # 3. MATERIALIZED VIEW: cohort_retention_mv
    # --------------------------------------------------------------------------
    op.execute("""
    CREATE MATERIALIZED VIEW IF NOT EXISTS cohort_retention_mv AS
    WITH customer_cohorts AS (
        SELECT
            c.org_id,
            c.id AS customer_id,
            date_trunc('month', c.created_at)::date AS cohort_month
        FROM customers c
    ),
    cohort_sizes AS (
        SELECT
            org_id,
            cohort_month,
            COUNT(customer_id) AS cohort_size
        FROM customer_cohorts
        GROUP BY org_id, cohort_month
    ),
    active_periods AS (
        SELECT DISTINCT
            md.org_id,
            md.customer_id,
            date_trunc('month', md.date)::date AS activity_month
        FROM mrr_daily md
        WHERE md.mrr_cents > 0
    ),
    retention AS (
        SELECT
            cc.org_id,
            cc.cohort_month,
            ap.activity_month,
            (EXTRACT(year FROM ap.activity_month) - EXTRACT(year FROM cc.cohort_month))::int * 12 +
            (EXTRACT(month FROM ap.activity_month) - EXTRACT(month FROM cc.cohort_month))::int AS period_month,
            COUNT(DISTINCT cc.customer_id) AS retained_customers
        FROM customer_cohorts cc
        JOIN active_periods ap ON cc.customer_id = ap.customer_id AND cc.org_id = ap.org_id
        WHERE ap.activity_month >= cc.cohort_month
        GROUP BY cc.org_id, cc.cohort_month, ap.activity_month
    )
    SELECT
        r.org_id,
        r.cohort_month,
        r.period_month,
        COALESCE(cs.cohort_size, 0) AS cohort_size,
        r.retained_customers,
        ROUND((r.retained_customers::numeric / NULLIF(cs.cohort_size, 0)::numeric) * 100, 2) AS retention_rate
    FROM retention r
    JOIN cohort_sizes cs ON r.org_id = cs.org_id AND r.cohort_month = cs.cohort_month;

    CREATE UNIQUE INDEX IF NOT EXISTS idx_cohort_retention_mv
        ON cohort_retention_mv (org_id, cohort_month, period_month);
    """)

    # --------------------------------------------------------------------------
    # 4. CURATED ANALYTICS SCHEMA VIEWS (AI TARGET)
    # --------------------------------------------------------------------------
    op.execute("""
    CREATE OR REPLACE VIEW analytics.v_mrr_summary AS
    SELECT
        d.org_id,
        d.date,
        COALESCE(SUM(d.mrr_cents), 0) AS total_mrr_cents,
        COALESCE(SUM(CASE WHEN m.movement_type = 'new' THEN m.amount_cents ELSE 0 END), 0) AS new_mrr_cents,
        COALESCE(SUM(CASE WHEN m.movement_type = 'expansion' THEN m.amount_cents ELSE 0 END), 0) AS expansion_mrr_cents,
        COALESCE(SUM(CASE WHEN m.movement_type = 'contraction' THEN m.amount_cents ELSE 0 END), 0) AS contraction_mrr_cents,
        COALESCE(SUM(CASE WHEN m.movement_type = 'churn' THEN m.amount_cents ELSE 0 END), 0) AS churn_mrr_cents,
        COALESCE(SUM(CASE WHEN m.movement_type = 'reactivation' THEN m.amount_cents ELSE 0 END), 0) AS reactivation_mrr_cents
    FROM mrr_daily d
    LEFT JOIN mrr_movements m ON d.org_id = m.org_id AND d.date = m.date AND d.subscription_id = m.subscription_id
    GROUP BY d.org_id, d.date;

    CREATE OR REPLACE VIEW analytics.v_customer_cohorts AS
    SELECT
        org_id,
        cohort_month,
        period_month,
        cohort_size,
        retained_customers,
        retention_rate
    FROM cohort_retention_mv;

    CREATE OR REPLACE VIEW analytics.v_plan_performance AS
    SELECT
        p.org_id,
        p.name AS plan_name,
        p.interval,
        p.amount_cents AS unit_price_cents,
        COUNT(DISTINCT si.subscription_id) AS active_subscribers,
        COALESCE(SUM(
            CASE
                WHEN p.interval = 'year' THEN (p.amount_cents * si.quantity) / 12
                WHEN p.interval = 'quarter' THEN (p.amount_cents * si.quantity) / 3
                WHEN p.interval = 'week' THEN (p.amount_cents * si.quantity * 52) / 12
                ELSE (p.amount_cents * si.quantity)
            END
        ), 0) AS total_mrr_cents
    FROM plans p
    JOIN subscription_items si ON p.id = si.plan_id AND p.org_id = si.org_id
    JOIN subscriptions s ON si.subscription_id = s.id AND si.org_id = s.org_id
    WHERE s.status IN ('active', 'trialing')
    GROUP BY p.org_id, p.name, p.interval, p.amount_cents;

    CREATE OR REPLACE VIEW analytics.v_at_risk_revenue AS
    SELECT
        i.org_id,
        i.stripe_id AS invoice_id,
        c.email AS customer_email,
        c.name AS customer_name,
        i.amount_due_cents,
        i.status,
        i.period_end AS due_date,
        i.created_at
    FROM invoices i
    JOIN customers c ON i.customer_id = c.id AND i.org_id = c.org_id
    WHERE i.status IN ('open', 'uncollectible')
       OR c.delinquent = TRUE;
    """)

    # --------------------------------------------------------------------------
    # 5. PERMISSIONS GRANT
    # --------------------------------------------------------------------------
    op.execute("""
    GRANT ALL ON ALL TABLES IN SCHEMA public TO revpulse_app;
    GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO revpulse_app;
    GRANT SELECT ON cohort_retention_mv TO revpulse_app;
    GRANT SELECT ON cohort_retention_mv TO revpulse_readonly;

    GRANT USAGE ON SCHEMA analytics TO revpulse_app, revpulse_readonly;
    GRANT SELECT ON ALL TABLES IN SCHEMA analytics TO revpulse_app, revpulse_readonly;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sub_items_org_sub', table_name='subscription_items')
    op.drop_table('subscription_items')
    op.drop_index('idx_mrr_movements_org_type', table_name='mrr_movements')
    op.drop_index('idx_mrr_movements_org_date', table_name='mrr_movements')
    op.drop_table('mrr_movements')
    op.drop_index('idx_mrr_daily_org_date', table_name='mrr_daily')
    op.drop_index('idx_mrr_daily_org_cust', table_name='mrr_daily')
    op.drop_table('mrr_daily')
    op.drop_index('idx_invoices_org_status', table_name='invoices')
    op.drop_index('idx_invoices_org_created', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('idx_subscriptions_org_status', table_name='subscriptions')
    op.drop_index('idx_subscriptions_org_cust', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('idx_alerts_org_triggered', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('idx_stripe_events_org_type', table_name='stripe_events')
    op.drop_table('stripe_events')
    op.drop_index(op.f('ix_stripe_connections_org_id'), table_name='stripe_connections')
    op.drop_table('stripe_connections')
    op.drop_index('idx_plans_org_id', table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_org_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_jobs_org_id'), table_name='jobs')
    op.drop_index('idx_jobs_run_at_pending', table_name='jobs', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('idx_jobs_org_status', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index('idx_customers_org_id', table_name='customers')
    op.drop_table('customers')
    op.drop_index('idx_alert_rules_org', table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index('idx_ai_query_org_created', table_name='ai_query_log')
    op.drop_table('ai_query_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
